apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "agentkernel.sandboxNamespace" . }}
  labels:
    {{- include "agentkernel.labels" . | nindent 4 }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
